export const actionTypes = {
    ADD_NEW_TASK: 'ADD_NEW_TASK',
    EDIT_TASK: 'EDIT_TASK',
    DELETE_TASK: 'DELETE_TASK',
    COMPLETED_TASK: 'COMPLETED_TASK',
    CLEAR_ALL_TASK: 'CLEAR_ALL_TASK'   
}

export const filterTypes = {
    FILTER_ALL: 'FILTER_ALL',
    FILTER_COMPLETED: 'FILTER_COMPLETED',
    FILTER_UNCOMPLETED: 'FILTER_UNCOMPLETED' 
}